"""store social and contact links

Revision ID: 057def3a766f
Revises: 38b3517994a9
Create Date: 2026-09-05 20:04:31.960768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057def3a766f'
down_revision = '38b3517994a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_social_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint(
        "platform IN ('instagram', 'facebook', 'tiktok', 'whatsapp', "
        "'website', 'email', 'phone')",
        name='ck_store_social_links_platform',
    ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'platform', name='uq_store_social_links_store_platform')
    )
    with op.batch_alter_table('store_social_links', schema=None) as batch_op:
        batch_op.create_index(
            'ix_store_social_links_store_id', ['store_id'], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_social_links', schema=None) as batch_op:
        batch_op.drop_index('ix_store_social_links_store_id')

    op.drop_table('store_social_links')
    # ### end Alembic commands ###
