"""user theme preference

Revision ID: 352560c629d4
Revises: 057def3a766f
Create Date: 2026-09-06 13:16:07.645724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352560c629d4'
down_revision = '057def3a766f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default backfills every existing row with 'system',
        # which is the right answer for a user who has never been asked.
        batch_op.add_column(
            sa.Column(
                'theme',
                sa.Enum('light', 'dark', 'system', name='theme_preference'),
                server_default='system',
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
