"""store accepts_orders_when_closed

Revision ID: 38b3517994a9
Revises: b42d5bab9108
Create Date: 2026-09-05 02:13:53.080597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b3517994a9'
down_revision = 'b42d5bab9108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepts_orders_when_closed', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('accepts_orders_when_closed')

    # ### end Alembic commands ###
