"""replace delivery fee with inside outside delivery fees

Revision ID: 38d18ed6663b
Revises: 499fb9222684
Create Date: 2026-07-20 17:19:57.888539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d18ed6663b'
down_revision = '499fb9222684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_payments_order_id",
            ["order_id"]
        )

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "inside_city_delivery_fee",
                sa.Numeric(10, 2),
                nullable=False,
                server_default="0.00"
            )
        )

        batch_op.add_column(
            sa.Column(
                "outside_city_delivery_fee",
                sa.Numeric(10, 2),
                nullable=False,
                server_default="0.00"
            )
        )
        batch_op.drop_column('delivery_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_fee', sa.NUMERIC(precision=10,
                                                                 scale=2),
                                                            nullable=False))
        batch_op.drop_column('outside_city_delivery_fee')
        batch_op.drop_column('inside_city_delivery_fee')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_payments_order_id",
            type_="unique"
        )

    # ### end Alembic commands ###
