"""shopping interests

Revision ID: 4348b45cc8e6
Revises: 9e006e631fe8
Create Date: 2026-09-04 14:10:02.321393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4348b45cc8e6'
down_revision = '9e006e631fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preferences_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preferences_id'], ['shopping_preferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preferences_id', 'category_id', name='uq_shopping_interests_preferences_category')
    )
    with op.batch_alter_table('shopping_interests', schema=None) as batch_op:
        batch_op.create_index('ix_shopping_interests_preferences_id', ['preferences_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_interests', schema=None) as batch_op:
        batch_op.drop_index('ix_shopping_interests_preferences_id')

    op.drop_table('shopping_interests')
    # ### end Alembic commands ###
