"""add delivery fields to stores

Revision ID: 4b3a1ba58eee
Revises: c2d457aee7f3
Create Date: 2026-07-08 12:31:15.214517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3a1ba58eee'
down_revision = 'c2d457aee7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('delivery_available', sa.Boolean(), nullable=False))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('delivery_available')
        batch_op.drop_column('delivery_fee')

    # ### end Alembic commands ###
