"""coupons and redemptions

Revision ID: 5b79a62a0984
Revises: fa263630a9da
Create Date: 2026-09-03 21:43:37.794755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b79a62a0984'
down_revision = 'fa263630a9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('per_user_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(discount_type = 'percentage' AND value >= 1 AND value <= 100) OR (discount_type = 'fixed' AND value > 0)", name='ck_coupons_value_range'),
    sa.CheckConstraint("discount_type IN ('percentage', 'fixed')", name='ck_coupons_discount_type'),
    sa.CheckConstraint('min_order_total IS NULL OR min_order_total >= 0', name='ck_coupons_min_order_total_non_negative'),
    sa.CheckConstraint('per_user_limit IS NULL OR per_user_limit >= 1', name='ck_coupons_per_user_limit_positive'),
    sa.CheckConstraint('usage_limit IS NULL OR usage_limit >= 1', name='ck_coupons_usage_limit_positive'),
    sa.CheckConstraint('used_count >= 0', name='ck_coupons_used_count_non_negative'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index('ix_coupons_store_id', ['store_id'], unique=False)

    op.create_table('coupon_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupon_redemptions', schema=None) as batch_op:
        batch_op.create_index('ix_coupon_redemptions_coupon_id_user_id', ['coupon_id', 'user_id'], unique=False)

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupon_code', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('coupon_code')

    with op.batch_alter_table('coupon_redemptions', schema=None) as batch_op:
        batch_op.drop_index('ix_coupon_redemptions_coupon_id_user_id')

    op.drop_table('coupon_redemptions')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index('ix_coupons_store_id')

    op.drop_table('coupons')
    # ### end Alembic commands ###
