"""drop payment_methods.number_hash, add card expiry

number_hash held an unsalted SHA-256 of the full card number. A PAN is
low-entropy — a known BIN plus a Luhn check digit leaves on the order of
a billion candidates — so that digest is reversible in seconds and the
column stored the card number in practice, against the CLAUDE.md rule.

The drop is deliberate destruction and it is the point: there is no
backfill and the downgrade cannot restore the digests, only re-create an
empty column. Nothing read the column — it was written in two places and
never queried, serialised or used for duplicate detection — so nothing
loses a capability.

exp_month / exp_year replace the part of the card number a customer
actually needs to tell two saved cards apart. Nullable, because rows that
predate this have no expiry and nothing here charges a card.

See docs/decisions/0024-no-card-data.md.

Revision ID: b42d5bab9108
Revises: 4348b45cc8e6
Create Date: 2026-09-05 01:34:12.195822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42d5bab9108'
down_revision = '4348b45cc8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp_month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exp_year', sa.Integer(), nullable=True))
        batch_op.drop_column('number_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_hash', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('exp_year')
        batch_op.drop_column('exp_month')

    # ### end Alembic commands ###
