"""two_factor_last_totp_counter on users

Revision ID: fa263630a9da
Revises: da88ef8e28e3
Create Date: 2026-09-03 20:29:21.345968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa263630a9da'
down_revision = 'da88ef8e28e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_last_totp_counter', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('two_factor_last_totp_counter')

    # ### end Alembic commands ###
